# -*- coding: utf-8 -*-
"""DragGAN Ro

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hyBT5cic5e2dE0kEEPRkOdvuO1rhGsZL
"""

!git clone https://huggingface.co/spaces/DragGan/DragGan-Inversion

# Commented out IPython magic to ensure Python compatibility.
# %cd DragGan-Inversion/

!pip install -r requirements.txt

!python visualizer_drag_gradio_inversion.py

